package event;

/**
 *
 * @author Anwin
 */
public class EventGuide {
    
    public static final String HUONG_DAN_SU_KIEN_TET = "|2|SỰ KIỆN TẾT NGUYÊN ĐÁN\n"
            + "1.Nấu Bánh\b"
            + "Người chơi tìm và thu thập Thịt heo, thúng nếp, thúng đậu xanh, lá dong để làm bánh Tét hoặc bánh Trưng\b"
            + "Hạ quái heo để lấy thịt heo\b"
            + "Hạ những quái còn lại để lấy Thúng nếp hoặc Thúng Đậu xanh\b"
            + "Tiêu diệt boss sự kiện Dragon để lấy Lá Dong và các item sự kiện khác\b"
            + "Có những item có thể mua tại Npc Karin Lân\b"
            + "Bánh Trưng Bánh Tét giúp chúng ta tăng chỉ số khi sử dụng.\n"
            + "2.Xin Chữ Đầu Năm và Ghép Chữ Đầu Năm\b"
            + "Người chơi đến shop Npc Karin Lân mua Thiệp đỏ và Thiệp Đỏ VIP để bắt đầu xin chữ\b"
            + "Sau khi xin đủ chữ thì ta hãy bắt đầu Ghép chữ tại Npc\b"
            + "Phần thưởng rất là hấp dẫn.\n"
            + "3.Bày Mâm Ngũ Quả\b"
            + "Người chơi thu thập Mãng cầu, Đu đủ, Quả xoài, Trái Sung, Quả dừa bằng cách farm quái tại các map\b"
            + "Bao lì xì rồng có bán tại Npc\b"
            + "Khi đủ ta tiến hành bày mâm ngũ quả, và tặng mâm ngũ quả cho Bà hạt mít để nhận thưởng.\n"
            + "4.Trang trí cây Nêu\b"
            + "Người chơi tiến hành thu thập Dây treo bánh, Câu đối, Lồng đèn treo cây bằng cách farm quái tại các map\b"
            + "Tiêu diệt boss sự kiện Dragon để nhận Dây pháo\b"
            + "Phần thưởng trang trí rất là hậu hĩnh\n"
            + "5.Dắt Thú Cưng\b"
            + "Người chơi tìm thú cưng tại các map\b"
            + "Sử dụng các vật phẩm trong shop để có thể dắt\b"
            + "Giao lân con và Bé Na cho Quy lão, Trưởng Lão, Vua để nhận quà\b"
            + "Giao Mèo đen và Pilong cho các Npc trước nhà để nhận quà\b"
            + "Phải pem chết thú cưng nó mới đi theo bạn, người khác cũng có thể cướp\n"
            + "6. Đua Top\b"
            + "Sử dụng lì xì sẽ nhận được 1 điểm đua top\b"
            + "Tặng cho các Npc sẽ nhận được 1 điểm đua top\b"
            + "Sử dụng pháo hoa sẽ nhận được 1 điểm đua top\b"
            + "Chơi các hoạt động Event để nhận được điểm sự kiện\n"
            + "7.Ngũ Hành Sơn Khai Mở\b"
            + "Hộ Tống Đường Tăng để nhận quà hấp dẫn\b"
            + "Giải cứu ngộ không nhận quà siêu Vip\n"
            + "8.Boss Sự Kiện\b"
            + "Boss Sự kiện Dragon xuất hiện tại các Map đảo\b"
            + "Boss thần tài xuất hiện tại các Map Làng\b"
            + "Phần quà khi tiêu diệt boss rất hấp dẫn, anh em mau nhanh tay.\n"
            + "9.Vòng Quay Thượng Đế\b"
            + "Lên thần điện để quay, có rất nhiều vật phẩm sự kiện mới cập nhật\n"
            + "10.Dành Cho Ai Lười Nhưng Giàu\b"
            + "Dùng Thỏi Vàng mà mua item sự kiện trên kênh thế giới\b"
            + "Đua top sự kiện nhận quà siêu Vip (Kết thúc sự kiện trao giải)\b"
            + "Đcm mệt quá, admin liệt kê thế thôi, còn lại tự vào game mà trải nhiệm\b"
            + "...HẾT...\b"
            + "CHÚC MỌI NGƯỜI CHƠI GAME VUI VẺ!\b"
            + "♡♡♡\b"
            + "---";
    
    public static final String HUONG_DAN_SU_KIEN_NOEL = "|2|SỰ KIỆN GIÁNG SINH\n"
            + "1.Trang Trí Cây Thông Noel\b"
            + "Người chơi tìm và thu thập Chuông, Quả châu, Ngôi sao, Dây kim tuyến, Móc treo noel để Trang trí cây thông Noel\b"
            + "Chuông, Quả châu, Ngôi sao ta có thể kiếm được bằng cách farm quái tại các map Sự Kiện\b"
            + "Dây kim tuyến thì ta tiêu diệt boss Sự kiện Chi Chi Tuần Lộc để nhận\b"
            + "Móc treo Noel có thể mua tại shop Npc Sự Kiện\n"
            + "2.Đổi Kẹo Lấy Quà\b"
            + "Người chơi tiến hành train quái tại các map để nhận kẹo giáng sinh\b"
            + "(Lưu ý: giới hạn 99 kẹo mỗi ngày)\b"
            + "Hoặc ta có thể nhận kẹo bằng cách mở hộp quà giáng sinh\n"
            + "3.Chế Tạo Người Tuyết và Người Tuyết Băng Giá\b"
            + "Người chơi qua map Sự kiện tìm và thu thập các vật phẩm sự kiện như là Mũi cà rốt, Tảng tuyết, Tay gỗ, Khăn choàng, Nón noel để chế tạo Người tuyết\b"
            + "Tảng Tuyết farm quái tại map Sự Kiện để nhận\b"
            + "Tay gỗ và Khăn Choàng tiêu diệt Boss Sự kiện Chi Chi để nhận\b"
            + "Mũi cà rốt tiêu diệt Golden Cooler ở map sự kiện để nhận\b"
            + "Nón noel mua tại Npc Sự Kiện\n"
            + "4.Đua Top Chế Tạo Người Tuyết và Người Tuyết Băng Giá\b"
            + "Người chơi tiến hành chế tạo để nhận 1 điểm đua top ở cả hai người tuyết\b"
            + "Hết sự kiện trao giải\n"
            + "5.Đua Top Quẹt Diêm\b"
            + "Người chơi tiến hành kiếm Hộp diêm thống nhất bằng cách farm quái tại map sự kiện\b"
            + "Sau đó mua Que diêm tại Npc Sự Kiện rồi quẹt\b"
            + "Sau đó sử dụng Que diêm bùng cháy để nhận quà và cộng 1 điểm đua top\n"
            + "6.Đua Top Trang Trí Cây Thông Noel\b"
            + "Trang trí cây thông để nhận 1 điểm đua top\b"
            + "Và đừng quên chúng tay hãy chung tay trang trí để nhận chúc phúc cho toàn máy chủ\n"
            + "7.Ông Già Noel Hạ Phàm\b"
            + "Ông già Noel sẽ xuất hiện tại các map đông người\b"
            + "Ông ban phát hộp quà giáng sinh, muốn nhặt được bạn phải đưa lại cho ông 1 tất, vớ giáng sinh\b"
            + "Tất, vớ giáng sinh ta có thể kiếm bằng cách farm quái tại map sự kiện\b"
            + "(Giới hạn 99 cái 1 ngày)\b"
            + "Hoặc mua ở shop Npc Sự Kiện\n"
            + "8.Dắt Pet Tuần Lộc về Trả cho Ông Già Noel\b"
            + "Tuần lộc của Ông già bị đi lạc\b"
            + "Nhiệm vụ của bạn là đưa Tuần lộc về trả cho ông Già Noel bằng cách\b"
            + "Chát 'ecec' hoặc 'ec ec' để Tuần lộc đi theo\b"
            + "(Lưu ý: Người chơi khác có thể cướp Tuần lộc của bạn)\b"
            + "Mang Tuần Lộc đến trả cho Ông già Noel\b"
            + "(Ông già Noel xuất hiện ngẫu nhiên tại các map, nên bạn hãy chịu khó nhé!)\n"
            + "9.Điều Ước Rồng Băng\b"
            + "Người chơi tiến hành thu thập ngọc rồng băng tại các map sự kiện với tỉ lệ farm quái ra được rất thấp\b"
            + "Hoặc tiêu diệt boss sự kiện GOKU SANTA để nhận siêu nhiều ngọc rồng băng\b"
            + "Điều ước xịn xò hihihihi\n"
            + "10.Đại Chiến Goku vs Broly\b"
            + "Hai boss sự kiện này sẽ xuất hiện tại các map băng của map sự kiện\b"
            + "Tiêu diệt boss nhận quà gì thì vào mà chơi\n"
            + "11.Thông Tin Boss\b"
            + "Gôku Santa và Chi Chi Tuần Lộc sẽ xuất hiện tại các map tân thủ ngoại trừ map up set kích hoạt thì boss sẽ không xuất hiện\b"
            + "Tiêu diệt boss nhận item sự kiện và cải trang xịn xò hấp dẫn\n"
            + "12.Đổi Điểm Sự Kiện\b"
            + "Mọi người tiến hành chơi các hoạt động Event để nhận 1 điểm sự kiện\b"
            + "Tiến hành tích góp và đổi quà Vip tại Npc ở Map sự kiện\n"
            + "13.Vòng Quay Thượng Đế\b"
            + "Lên thần điện để quay, có rất nhiều vật phẩm sự kiện mới cập nhật\n"
            + "14.CHÚC ANH EM CHƠI GAME VUI VẺ\b"
            + "Còn nhiều mà admin lười quá, tự vào trải nghiệm đeee\b"
            + "Bái Bai\b"
            + "Chúc Anh Em Chơi Game Vui Vẻ\b"
            + "♡♡♡\b"
            + "---";
    
    public static final String HUONG_DAN_SU_KIEN_VU_LAN = "|2|SỰ KIỆN LỄ VU LAN\n"
            + "1.Hồi Sinh Lích Tên\b"
            + "Người chơi tiến hành thu thập Hồn ma, Bình phép, Lọ nước hồi sinh, Bùa hồi sinh để hồi sinh Lích Tên\b"
            + "Bình Phép và Lọ Nước Hồi Sinh ta thụp thập bằng cách tiêu diệt Boss Piikkon tại Map Sự kiện\b"
            + "Bùa hồi sinh mua tại Shop Npc sự kiện\b"
            + "Hồn ma thu thập bằng cách tiêu diệt quái tại map Sự Kiện (Dùng máy dò linh hồn để thu thập nhanh hơn)\b"
            + "Lưu ý: Hồn ma rất nhạy cảm nên rất dễ thoát ra ngoài, Hãy luôn giữ Bình phép trong người để có thể lưu trữ Hồn ma một cách an toàn nhất có thể!\n"
            + "2.Ráp Hoa Đăng\b"
            + "Để ráp cần khung tre, nến, giấy màu, lời chúc\b"
            + "Khung tre và Giấy màu ta có thể farm quái tại map sự kiện để nhận\b"
            + "Nến và Lời chúc mua tại Npc Sự kiện\n"
            + "3.Đua Top Ráp Hoa Đăng\b"
            + "Sau khi ráp thì sử dụng để cộng 1 điểm đua top\b"
            + "Hết sự kiện trao giải\n"
            + "4.Đua Top Pháo Hoa\b"
            + "Mua pháo hoa tại Npc Sự Kiện\b"
            + "Sử dụng để nhận 1 điểm đua top\b"
            + "Kết thúc sự kiện Trao giải\n"
            + "5.Vòng Quay Thượng Đế\b"
            + "Lên thần điện để quay, có rất nhiều vật phẩm sự kiện mới cập nhật\n"
            + "6.CHÚC ANH EM CHƠI GAME VUI VẺ\b"
            + "Tự vào trải nghiệm nhé anh em\b"
            + "Admin nói đến đây thôi\b"
            + "♡♡♡\b"
            + "---";
    
    public static final String HUONG_DAN_SU_KIEN_HALLOWEEN = "|2|SỰ KIỆN HALLOWEEN\n"
            + "1.Làm Hộp Kẹo Ma Quỷ\b"
            + "Người chơi tiến hành thu thập Kẹo bàn tay, Giỏ đựng kẹo trái bí, Giấy trang trí Halloween\b"
            + "Kẹo bàn tay có nhận nhận free tại các Npc hàng ngày hoặc farm quái tại các map để nhận, Hp quái càng cao tỷ lệ nhận càng cao\b"
            + "Giỏ đựng kẹo và Giấy trang trí mua tại Shop NPC sự kiện\n"
            + "2.Đua Top Mở Hộp Kẹo Ma Quỷ\b"
            + "Sử dụng Hộp Kẹo khi làm ra để nhận 1 điểm đua top\b"
            + "Hết sự kiện trao giải\n"
            + "3.Ước Quà\b"
            + "Người chơi đến gặp Npc Sự kiện\b"
            + "Dùng 50 hồng ngọc để ước nhận quà\n"
            + "4.Boss Hoá Xương Ma\b"
            + "Các boss xuất hiện tại các map ngẫu nhiên ngoại trừ các map up sét kích hoạt\b"
            + "Boss có thể hoá xương các bạn\b"
            + "Tiêu diệt boss nhận bí ngô để đổi cải trang Vip\b"
            + "Tiêu diệt boss để nhận ngọc rồng Bí Ngô\b"
            + "(Lưu ý: Trong hành trang của bạn phải có item giỏ đựng kẹo trái bí thì khi tiêu diệt boss thì nó mới rơi, nếu nó rơi mà trong hành trang bạn không có item giỏ đựng thì cũng không nhặt được)\b"
            + "Các boss sẽ rơi ngọc rồng bí mặc định theo boss đó, không rơi ngẫu nhiên ngọc rồng bí\n"
            + "5.Điều Ước Rồng Xương\b"
            + "Thu thập ngọc rồng bí Bằng cách tiêu diệt quái tại các map (Phải sử dụng item máy dò ngọc rồng tại Npc sự kiện mới có thể nhận được) tiêu diệt quái Hp càng cao thì tỉ lệ nhận càng cao\b"
            + "Tiêu diệt Boss để nhận ngọc 1-3 sao, farm quái nhận 4-7 sao\n"
            + "6.Đua Top Mở Thiệp Halloween\b"
            + "Người chơi mua thiệp tại Npc Sự Kiện\b"
            + "Sử dụng mỗi thiệp để nhận 1 điểm đua top tương ứng\b"
            + "Hết sự kiện trao giải\n"
            + "7.Đổi Điểm Sự Kiện\b"
            + "Tiến hành chơi các hoạt động Event để nhận điểm sự kiện\b"
            + "Dùng điểm sự kiện đổi quà vip ở shop Npc Sự kiện\n"
            + "8.Boss Sự Kiện\b"
            + "Trong thời gian diễn ra sự kiện xuất hiện Boss khủng tại rừng nấm và rừng xương\b"
            + "Boss siêu mạnh, khi diệt boss có tỉ lệ nhận cải trang chỉ số cực khủng\b"
            + "Hãy kêu gọi đồng đội để có thể cùng nhau diệt boss\n"
            + "9.Vòng Quay Thượng Đế\b"
            + "Lên thần điện để quay, có rất nhiều vật phẩm sự kiện mới cập nhật\n"
            + "10.CHÚC ANH EM CHƠI GAME VUI VẺ\b"
            + "Nói thế thôi, vào game mà trải nghiệm nhiều thứ mới\b"
            + "Bye Bye anh em, Chúc anh em chơi game vui vẻ\b"
            + "♡♡♡\b"
            + "---";
    
    public static final String HUONG_DAN_SU_KIEN_QUOC_TE_83 = "|2|SỰ KIỆN QUỐC TẾ PHỤ NỮ\n"
            + "1.Chế Tạo Hộp Đựng Quà\b"
            + "Người chơi farm quái tại các map ngoài trừ 3 map sau làng để nhận giấy màu\b"
            + "Sử dụng x99 giấy màu để chế tạo Hộp đựng quà bằng cách ấn sử dụng\n"
            + "2.Tặng Hộp Quà\b"
            + "Người chơi tiến hành thu thập Hoa hồng giấy, Socola trái tim, Hộp đựng quà, Nơ trang trí bằng cách\b"
            + "Hộp đựng quà thu thập bằng cách chế tạo từ giấy màu\b"
            + "Hoa hồng giấy nhận bằng cách tiêu diệt quái tại các map đồi sau làng\b"
            + "Mặc cải trang NỮ để nhận Socola trái tim khi tiêu diệt quái\n"
            + "3.Tặng Hoa Hồng\b"
            + "Để chế tạo hoa hồng cần Đất trồng cây, Ống tre nước, Túi Hạt giống, Chậu Đất, Thuốc tăng trưởng\b"
            + "Đất trồng cây ta farm quái ở các map để nhận\b"
            + "Ống tre nước thì khi chế tạo hộp quà nhẹ nhàng nhận được ngẫu nhiên số lượng ít Ống tre\b"
            + "Khi chế tạo hộp quà chỉn chu sẽ nhận số lượng nhiều Ống tre\b"
            + "Túi Hạt giống, Chậu Đất, Thuốc tăng trưởng ta có thể mua tại Npc Sự kiện\b"
            + "[Hoa hồng có thể kiếm free bằng cách hái hoa tại các map, hoa hồng sẽ xuất hiện ngẫu nhiên, ai may mắn thì hái được]\n"
            + "4.Đua Top Tặng Hoa Hồng\b"
            + "Người chơi tặng hoa cho Npc Sự kiện hoặc Npc Chi Chi, mỗi 1 bông = 1 điểm đua top\b"
            + "Hết Sự kiện trao giải\n"
            + "5.Đua Top Mở Thiệp 8-3\b"
            + "Người chơi mua thiệp tại npc sự kiện\b"
            + "Sử dụng nhận quà và nhận 1 điểm đua top\b"
            + "Hết sự kiện trao giải\n"
            + "6.BUFF Toàn Máy Chủ\b"
            + "Người chơi tặng hoa để nhận điểm buff\b"
            + "Đây là dành cho toàn máy chủ\b"
            + "Mọi người chung tay để nhận Chúc phúc cho toàn máy chủ\b"
            + "(Có thể cộng dồn, không giới hạn)\n"
            + "7.Đổi Điểm Sự Kiện\b"
            + "Tiến hành làm những hoạt động event để nhận điểm sự kiện\b"
            + "Sau đó dùng điểm đổi tại Npc sự kiện\b"
            + "Còn đâu tự vào game trải nhiệm nhé anh em!\n"
            + "8.Vòng Quay Thượng Đế\b"
            + "Lên thần điện để quay, có rất nhiều vật phẩm sự kiện mới cập nhật\n"
            + "9.HẾT RỒI...\b"
            + "Chỉ muốn nói là\b"
            + "CHÚC ANH EM CHƠI GAME VUI VẺ\b"
            + "♡♡♡\b"
            + "---";
    
    public static final String HUONG_DAN_SU_KIEN_TRUNG_THU = "|2|SỰ KIỆN TRUNG THU\n"
            + "1.Thu Thập Đuôi Khỉ\b"
            + "Người chơi tiến hành mua vật phẩm Ánh trăng tròn trong shop Npc Sự kiện\b"
            + "Sử dụng và đợi 1 lúc để cho khỉ đột xuất hiện\b"
            + "Tiêu diệt boss sẽ nhận được ngẫu nhiên 1-3 đuôi khỉ\b"
            + "Đuôi khỉ có thể sử dụng để nhận x2 exp trong 30p (không giới hạn)\b"
            + "Hoặc dùng để đổi vật phẩm trong Shop Sự Kiện\n"
            + "2.Thu Thập Cà Rốt\b"
            + "Người chơi tiến hành tìm Thỏ đại ka, tiêu diệt hắn để nhận ngẫu nhiên Cà rốt\b"
            + "Boss khá mạnh, khi bị biến thành Cà rốt, sức đánh sẽ bị giảm đi 15%\b"
            + "Hoặc mua item thỏ ngọc trong shop Npc sự kiện để có thể tìm thỏ nhanh hơn\b"
            + "Dùng Cà rốt để đổi quà hoặc ước nguyện\n"
            + "3.Nấu Bánh Trung Thu\b"
            + "Người chơi tiến hành thu thập nguyên liệu Bột mì, Đậu xanh, Trứng vịt muối, Gà quay nguyên con, Hạt sen\b"
            + "Vật phẩm Hạt sen ta farm quái tại các map quái 1k5 hp để nhận\b"
            + "Còn những vật phẩm còn lại ngoại trừ map quái 1k5 hp thì farm map nào cũng nhận được\b"
            + "Tiến hành nấu bánh và đem bánh qua đổi cho npc sự kiện để nhận quà hấp dẫn\n"
            + "4.Đua Top Nấu Bánh\b"
            + "Trong thời gian diễn ra sự kiện\b"
            + "Cứ nấu mỗi 1 loại bánh là được 1 điểm sự kiện (kết thúc sự kiện trao giải)\n"
            + "5.Đổi Thỏ Cưng\b"
            + "Người chơi dùng bánh trung thu đã chế tạo ra được để đổi lấy Pet Sự kiện\b"
            + "Pet chỉ số vip nha, có tỷ lệ cao vĩnh viễn\n"
            + "6.Thắp sáng Cây Lồng Đèn\b"
            + "Người chơi tiến hành tìm kiếm lồng đèn bằng cách farm quái tại các map\b"
            + "Hoặc mua tại Npc sự kiện\b"
            + "Sau đó thì treo đèn ở Npc sự kiện tại các map làng để nhận quà\n"
            + "7.Đua Top Mở Hộp Bánh Trung Thu\b"
            + "Người chơi tiến hành đổi hộp bánh ở shop điểm sự kiện với 50 điểm\b"
            + "Với mỗi 1 hộp là cộng 1 điểm (kết thúc sự kiện trao giải)\n"
            + "8.Shop Sự Kiện\b"
            + "Người chơi chăm chỉ hoạt động chơi các sự kiện sẽ nhận được điểm sự kiện\b"
            + "Dùng điểm sự kiện để đổi quà hấp dẫn!\n"
            + "9.Điều Ước\b"
            + "Mỗi ngày tại Npc Thỏ các cư dân sẽ có 1 lượt miễn phí để ước\b"
            + "Hoặc ta có thể bỏ ra hồng ngọc, Cà rốt để ước\b"
            + "Phần quà mới lạ và hấp dẫn\n"
            + "10.Omega vs Gogeta\b"
            + "Chọn phe và tiêu diệt phe còn lại\b"
            + "Tiêu diệt ai thì nhận cải trang người đó với chỉ số siêu Vip\b"
            + "Có tỷ lệ vĩnh viễn\b"
            + "Có 50% rơi vật phẩm đeo lưng xịn xò\n"
            + "11.Nhật thần vs Nguyệt Thần\b"
            + "Chọn phe và tiêu diệt phe còn lại\b"
            + "Tiêu diệt ai thì nhận cải trang người đó với chỉ số siêu Vip\b"
            + "Boss này rơi hạt sen với số lượng ngẫu nhiên\b"
            + "Nhưng lưu ý: trong hành trang phải có kiếm gỗ thì mới có thể gây sát thương và khi tiêu diệt mới có thể rơi cải trang\b"
            + "Sau khi tiêu diệt boss, bạn sẽ bị mất đi 1 thanh kiếm gỗ\b"
            + "Kiếm gỗ mua tại npc giá siêu rẻ\n"
            + "12.Rước Đèn Bang Hội\b"
            + "Người chơi tiến hành vào map bang hội\b"
            + "Lưu ý: phải toàn bộ thành viên trong bang online và đứng cùng khu vực và phải mặc lồng đèn bất kỳ thì mới có thể rước đèn được\b"
            + "Rước đèn sẽ nhận được x2 exp cho toàn bang\n"
            + "13.Vòng Quay Thượng Đế\b"
            + "Lên thần điện để quay, có rất nhiều vật phẩm sự kiện mới cập nhật\n"
            + "14.HẾT\b"
            + "CHÚC ANH EM CHƠI GAME VUI VẺ\b"
            + "♡♡♡\b"
            + "---";
    
    public static final String HUONG_DAN_SU_KIEN_HUNG_VUONG = "|2|SỰ KIỆN GIỖ TỔ HÙNG VƯƠNG\n"
            + "1.Nhận Quà Hàng Ngày\b"
            + "Hàng ngày đến npc Hùng Vương tại các đảo để nhận quà miễn phí\n"
            + "2.Dâng Sính Lễ\b"
            + "Người chơi tiến hành thu thập Ngà Voi, Cựa Gà, Hồng mao\b"
            + "Item sự kiện xuất hiện khi tiêu diệt Voi 9 Ngà, Gà 9 Cựa, Ngựa 9 Hồng Mao\b"
            + "Quái sẽ xuất hiện tại các map up sét kích hoạt, hoặc trong map sự kiện\n"
            + "3.Nấu Bánh Trung Thu\b"
            + "Người chơi tiến hành thu thập nguyên liệu Bột mì, Đậu xanh, Trứng vịt muối, Gà quay nguyên con, Hạt sen\b"
            + "Vật phẩm Hạt sen ta farm quái tại các map quái 1k5 hp để nhận\b"
            + "Còn những vật phẩm còn lại ngoại trừ map quái 1k5 hp thì farm map nào cũng nhận được\b"
            + "Tiến hành nấu bánh và đem bánh qua đổi cho npc sự kiện để nhận quà hấp dẫn\n"
            + "4.Dâng Bánh\b"
            + "Trong thời gian diễn ra sự kiện\b"
            + "Làm Các sự kiện để nhận bánh rồi dâng cho vua hùng\n"
            + "5.Đổi Dưa Hấu\b"
            + "Mỗi 10p tại Npc Hùng Vương ở đảo kame sẽ cho ngẫu nhiên 1 hạt giống\b"
            + "Ai may mắn sẽ nhận được hạt giống\b"
            + "Sử dụng hạt giống để trồng dưa tại nhà\b"
            + "Mỗi 24h dưa sẽ chín, thu thập dưa rồi mang đến đổi lấy hồng ngọc tại npc Vua hùng\n"
            + "6.Đại chiến Godzila vs Kong\b"
            + "Mua rada phóng xạ để vào map sự kiện\b"
            + "Tiêu diệt Godzila hoặc Kong để nhận vật phẩm sự kiện cũng như pet\b"
            + "Quái sẽ hồi sinh 10p /1 lần\n"
            + "7.Đua Top Sự kiện\b"
            + "Vào game mà xem!\n"
            + "8.Shop Sự Kiện\b"
            + "Vào game mà xem!\n"
            + "9.Đại chiến Sơn Tinh vs Thuỷ Tinh\b"
            + "Chọn phe và tiêu diệt phe còn lại\b"
            + "Tiêu diệt ai thì nhận cải trang người đó với chỉ số siêu Vip\b"
            + "Có tỷ lệ vĩnh viễn\b"
            + "Có 50% rơi vật phẩm đeo lưng xịn xò\n"
            + "10.HẾT\b"
            + "Admin càng ngày càng lười viết thông tin sự kiện, anh em thông cảm, vào game mà tìm hiểu nhé!\b"
            + "CHÚC ANH EM CHƠI GAME VUI VẺ\b"
            + "♡♡♡\b"
            + "---";
    
    public static final String HUONG_DAN_SU_KIEN_BLACK_FRIDAY = "|2|SỰ KIỆN BLACK FRIDAY\n"
            + "Thật ra sự kiện cũng trả có gì đâu\b"
            + "Chủ yếu trong shop mở bán những vật phẩm ít xuất hiện trong game mà chỉ nhận được bằng cách mua trong shop sự kiện Black Friday\b"
            + "Nói chung sự kiện này để anh em xả láng, xả tài nguyên\b"
            + "Sự kiện này đua top quà căng lắm nè...\b"
            + "CHÚC ANH EM CHƠI GAME VUI VẺ\b"
            + "♡♡♡\b"
            + "---";
    
}
